spring:
  application:
    name: user-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: User Service

server:
  port: 9789
logging:
  level:
    root: debug
    ##root: off
    ##com.eleiatech:debug ## bu şekilde diyerek daha az ve daha az karışık log görebiliriz.

---
spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      uri: http://localhost:8889
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: ##### todo buraya microservice olması için ne koyulması gerektiği araştırılacak.



eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/